### ISSUE TITLE
Logger Error: error rotatorring: error renaming log

### ISSUE THREAD

**Issue by YouveGotMeowxy** [hotio/unpackerr#22]
I'm getting this error in my logs:

    Logger Error: error rotatorring: error renaming log: rename /config/unpackerr.log /config/unpackerr-2024-01-21T10-40-07.115.log: device or resource busy

![image](https://github.com/hotio/unpackerr/assets/39491297/4620d67f-4458-42c3-9975-1941c5f3cbf8)

```
  unpackerr:
    image: 'ghcr.io/hotio/unpackerr:release'
    hostname: 'unpackerr'
    environment:
      TZ: 'America/Chicago'
      PUID: '1000'
      PGID: '1000'
    volumes:
      - '/opt/docker/configs/unpackerr/config:/config:rw'
      - '/mnt/e/Docker/Logs/unpackerr/unpackerr.log:/config/unpackerr.log:rw'
      - '/mnt/e/Media/.downloads:/Media/.downloads:rw'
      # + -- Extra folder to monitor -- + #
      - '/mnt/e/Media/Unpack:/Media/unpack:rw'
    networks:
      - 'download'
    deploy:
        mode: 'replicated'
        replicas: 1
        placement:
          constraints:
            - 'node.labels.Cloud == true'
        restart_policy:
          condition: 'any'
```
Any ideas?
